### ISSUE TITLE
pylint error

### ISSUE THREAD

**Issue by bjxpolarbear** [cgohlke/molmass#4]
The package works well.
However, the when I use pylint with the satement as follows:
`Formula("C2H4O").isotope.mass`
it pop an error says:
`Method 'isotope' has no 'mass' member`

**Comment by bjxpolarbear** [comment]
Is there a way to make it compatible with pylint?

**Comment by cgohlke** [comment]
See http://pylint.pycqa.org/en/latest/user_guide/message-control.html
