### ISSUE TITLE
Notation of C13 and N15 in f.formula?

### ISSUE THREAD

**Issue by gmhhope** [cgohlke/molmass#6]
Hi Dr. Christoph Gohlke,

Are there ways to properly denote isotopic carbon or nitrogen like 13C, 15N in molmass?

Thanks very much!

Best,
Minghao

**Comment by cgohlke** [comment]
Try [[13C]](https://www.lfd.uci.edu/~gohlke/molmass/?q=%5B13C%5D) and [[15N]](https://www.lfd.uci.edu/~gohlke/molmass/?q=%5B15N%5D).
