### ISSUE TITLE
Adding factional wt of element

### ISSUE THREAD

**Issue by code4Siddharth** [cgohlke/molmass#7]
How can we enter the formula of compounds like FeO2.33 or A0.2B0.8Se etc.?

**Comment by cgohlke** [comment]
Do you mean to calculate a formula by its relative element weights, e.g. [`Fe: 1, O:2.33`](https://www.lfd.uci.edu/~gohlke/molmass/?q=Fe%3A+1%2C+O%3A2.33)?

**Comment by code4Siddharth** [comment]
Yes, for example, if I want to calculate the molecular mass of Sr_0.5La_0.5TiO_3 it gives an error  
FormulaError: count is zero
Sr0(La0)5(TiO3)5
......^

**Comment by cgohlke** [comment]
Sorry, molmass formulas can not contain fractional numbers.
